[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip ATSAMD51J19A --speed 20000'
rustflags = [
  # LLD (shipped with the Rust toolchain) is used as the default linker
  "-C", "link-arg=-Tlink.x",
  "-C", "embed-bitcode=yes",
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tdefmt.x", # uncomment if using defmt

  # Select one of these configs to measure a certain code section.
  # Results are printed with defmt.
  "--cfg", "bench_arrival_handler",
  # "--cfg", "bench_dispatcher_exit",
  # "--cfg", "bench_pop_cs",
  # "--cfg", "bench_dispatcher_exit_cs",

  # if you run into problems with LLD switch to the GNU linker by commenting out
  # this line
  # "-C", "linker=arm-none-eabi-ld",

  # if you need to link to pre-compiled C libraries provided by a C toolchain
  # use GCC as the linker by commenting out both lines above and then
  # uncommenting the three lines below
  # "-C", "linker=arm-none-eabi-gcc",
  # "-C", "link-arg=-Wl,-Tlink.x",
  # "-C", "link-arg=-nostartfiles",
]
