[default.general]
chip = "ATSAMD51J19A"

[default.rtt]
enabled = true
# Give ourselves time to attach gdb
timeout = 100000

[default.reset]
enabled = true
halt_afterwards = true

[default.gdb]
enabled = true
gdb_connection_string = "[::1]:1337"